### ISSUE TITLE
Use column name instead of programatical name

### ISSUE THREAD

**Issue by eknori** [klehmann/domino-jna#2]
First of all, great stuff.

Did you ever find a way to use the column name instead of the progamatical name to get the value from a view column?

I see an issue when you use the method with an application where you do not have control of the design.
You can never be sure, that the programatical name will never change.

**Comment by klehmann** [comment]
I rewrote the project code to always use the programmatic names because that's what is returned in the summary buffer when READ_MASK_SUMMARY is used. In general it is better to use READ_MASK_SUMMARYVALUES instead, because more data fits into the 64 K summary buffer (contains values only and no duplicate column names), but for NIFFindByKeyExtended2 in 9.0.1, only READ_MASK_SUMMARY is supported.

With READ_MASK_SUMMARYVALUES is used, I first scan the columns (https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/main/java/com/mindoo/domino/jna/NotesCollection.java#L1943) and read the programmatic names using the legacy Java API (haven't written the code to do this in C yet) to be able to unify both API calls.

It would be possible to always scan the columns and translate the column name argument to the right index (for READ_MASK_SUMMARYVALUES) / programmatic name (for READ_MASK_SUMMARY). I have that on my list, because I want to use the Domino JNA for a project where I am currently using column names instead of programmatic names. But I haven't had the time to work on this.
