### ISSUE TITLE
Accessing rich text with C / C++ code

### ISSUE THREAD

**Issue by brianstittsr** [klehmann/domino-jna#33]
Hi am looking for guidance on a pet project. I noticed that your project can perform rich text to HTML conversions. My project is based on using C / C++. How can I use your Java project with my current code?

Can you send me an email at brianstittsr@gmail.com with your response?

Thanks,

**Comment by klehmann** [comment]
Others might be interested in the response as well. ;-)

When your project is already written in C/C++, the best way is probably to use Domino's C API directly instead of building a bridge to Java code.

The latter would be possible by launching a JVM from C via ```JNI_CreateJavaVM``` using the Invocation API described here:
https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/invocation.html

We could build such a bridging solution as a dev project and have done this in the past, but I cannot provide an easy sample for that.
