### ISSUE TITLE
Problem with richtext-items after version 0.9.27

### ISSUE THREAD

**Issue by glasen** [klehmann/domino-jna#49]
Hi,

I'm currently trying to use a newer version of Domino-JNA. It seems that since version 0.9.28 richtext-handling is broken. 

Version 0.9.27

System.out.println(note.getRichtextContentAsText("Body"));

--> (See attached file: 1234.pdf) - 1234.pdf

System.out.println(note.getItemValue(("Body")));

-> com.mindoo.domino.jna.errors.UnsupportedItemValueError: Use NotesNote.getRichtextNavigator() to read richtext item data

Version 0.9.28 and above:

System.out.println(note.getRichtextContentAsText("Body"));

--> Empty string

System.out.println(note.getItemValue(("Body")));

-> java.lang.NegativeArraySizeException: -136

**Comment by klehmann** [comment]
Hi! Sorry for the late response. I cannot reproduce your issue. Please send me the full stacktrace for the java.lang.NegativeArraySizeException issue and if possible a copy of the document. In my test, CDTEXT extraction from richtext works fine with the latest code from Github (checked out via Git, but I am pretty sure this has not changed since the last release).
