### ISSUE TITLE
Connect to db from already connected db

### ISSUE THREAD

**Issue by sattam-datum** [klehmann/domino-jna#61]
I need a way to connect to db  from already connected one,
I have part already connected to notes by standard lotus.domino.Database so instead of writing the credentials and file path again
to this library,
I suggest to provide new constructor from NotesDatabase to accept lotus.domino.Database object and internally you will take the needed info

**Comment by klehmann** [comment]
There is ```LegacyAPIUtils.toNotesDatabase(Database db)``` to reuse an existing DB handle (
https://github.com/klehmann/domino-jna/blob/master/domino-jna/src/main/java/com/mindoo/domino/jna/utils/LegacyAPIUtils.java#L395) but you have to check if this works in your environment since it uses a function in the IBM/HCL NAPI plugin. I haven't added a constructor for lotus.domino.Database to the project because the long-term goal is to remove any dependency to Notes.jar at all, so LegacyAPIUtils will eventually be moved to another project.
