### ISSUE TITLE
Rich text attachment name

### ISSUE THREAD

**Issue by sattam-datum** [klehmann/domino-jna#62]
Attachment file name in most of cases is correct  and in case of duplicate filename 
file name will be like :  file1.002.docx/file1.docx so i can get the first part of the name
but
some attachments filename will be like :  ATT8TYAQ.docx/testFile.docx
ATT7B4UN.xlsx/testFile2.xlsx  and there are no duplicate in attachment names
so the actual file name is the second part.

so what is the problem for these files and is there common way to get the needed name ?

**Comment by klehmann** [comment]
Renaming filenames in case of duplicates is by design, although my filenames are a bit more readible compared to those of the Notes.jar. See this code block in ```NotesNote.attachFile(...)```:

```java
//make sure that the unique filename is really unique, since it will be used to return the NotesAttachment object
List<Object> existingFileItems = FormulaExecution.evaluate("@AttachmentNames", this);
String reallyUniqueFileName = uniqueFileNameInNote;
if (existingFileItems.contains(reallyUniqueFileName)) {
	String newFileName=reallyUniqueFileName;
	int idx = 1;
	while (existingFileItems.contains(reallyUniqueFileName)) {
		idx++;

		int iPos = reallyUniqueFileName.lastIndexOf('.');
		if (iPos==-1) {
			newFileName = reallyUniqueFileName+"_"+idx;
		}
		else {
			newFileName = reallyUniqueFileName.substring(0, iPos)+"_"+idx+reallyUniqueFileName.substring(iPos);
		}
		reallyUniqueFileName = newFileName;
	}
}
```

There is a difference between the filename that is encoded into the $File item (returned by ```@AttachmentNames```) and the label that you see in the richtext item. Technically it would probably be possible to create two $File items with the same filename (since it's just a FILEOBJECT data structure in the item value), but it does not make much sense, you could not access the file data via filename anymore and would get some problems with the Notes.jar API.

The richtext label can be anything you want, the C API / Domino JNA even has some formatting options for the text (all that is available in the C API) and you can specify your own preview icon with any icon size. What you see in the richtext is just a link to the $File item which itself contains the Record Relocation Vector (RRV) of an object in the NSF that contains the file data.

So you could even have two richtext items pointing to the same file or move a file between richtext items without detaching/attaching anything to disk.

**Comment by sattam-datum** [comment]
I told you, I don't have problems with renaming in case of duplicate names,
the problem with some unique files but in code file name is return like this:   ATT123.docx/originalname.docx
so is this name is returned like this from notes?

**Comment by klehmann** [comment]
I‘ve never seen filenames with a /. I only know the ATTxxx filenames. But I try to avoid adding duplicate filenames to documents. Maybe that‘s a new way to create the unique filename and keep the original filename at the same time.

**Comment by sattam-datum** [comment]
Are ATTxxx filenames something special ?

**Comment by klehmann** [comment]
No. The Notes.jar renames the file when an attachment with the same name already exists.
